project_id = "hwwvtxyezhgmhyxjpnvl"

[functions.notify-waitlist]
verify_jwt = false

[functions.detect-available-spots]
verify_jwt = false

[functions.bulk-create-students]
verify_jwt = true

[functions.bulk-create-classes]
verify_jwt = true

[functions.intelligent-bulk-create-classes]
verify_jwt = true

[functions.stripe-connect]
verify_jwt = true

[functions.stripe-login-link]
verify_jwt = true
[functions.send-test-whatsapp]
verify_jwt = false

[functions.send-class-reminder-whatsapp]
verify_jwt = false

[functions.send-daily-class-reminders]
verify_jwt = false

[functions.send-attendance-reminders]
enabled = true
verify_jwt = false
import_map = "./functions/send-attendance-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-attendance-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-attendance-reminders/*.html" ]
